<a href="https://colab.research.google.com/github/rsys-adsingh/Machine-Learning/blob/main/study/Chapter_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Topic 1: What is Data Preprocessing?

### 1. Definition

Data Preprocessing is the process of cleaning, transforming, and preparing raw data into a format suitable for Machine Learning algorithms.

Simply put,

**Data Preprocessing = Converting Raw Data into ML-Ready Data**

### 2. Why do we need Data Preprocessing?

Real-world data is rarely perfect.

It often contains

*   Missing values
*   Duplicate rows
*   Wrong values
*   Different formats
*   Outliers
*   Different scales

Machine Learning algorithms expect clean numerical data.

**Example**

Raw Dataset

| Age | Salary | City | Purchased |
|-----|--------|------|-----------|
| 25  | 50000  | Delhi| Yes       |
| NULL| 60000  | Mumbai| No        |
| 25  | 50000  | Delhi| Yes       |
| 999 | 70000  | Delhi| Yes       |

**Problems**

❌ Missing value

❌ Duplicate row

❌ Outlier

This dataset should not be directly used for training.

### 3. Formula

There is no mathematical formula.

Conceptually

Raw Data

↓

Cleaning

↓

Transformation

↓

Encoding

↓

Scaling

↓

ML Ready Data

### 4. Data Preprocessing Pipeline ⭐⭐⭐

A typical preprocessing workflow is

Raw Data

↓

Missing Values

↓

Duplicate Removal

↓

Data Cleaning

↓

Outlier Handling

↓

Encoding

↓

Feature Scaling

↓

Feature Engineering

↓

Train/Test Split

↓

Machine Learning Model

This is the order followed in most ML projects.

### 5. Working

Suppose we receive customer data.

Customer Data

↓

Remove Missing Values

↓

Fix Wrong Values

↓

Convert Categories

↓

Scale Numbers

↓

Train Model

The algorithm now receives clean data.

### 6. Where is it used?

Every Machine Learning project.

Examples

*   Banking
*   Healthcare
*   Insurance
*   Fraud Detection
*   Recommendation Systems
*   NLP
*   Computer Vision

### 7. Advantages

✅ Improves model accuracy

✅ Reduces bias

✅ Faster convergence

✅ Better generalization

✅ Better feature quality

### 8. Limitations

*   Time-consuming
*   Domain knowledge required
*   Wrong preprocessing can reduce accuracy
*   Different datasets require different preprocessing strategies

### 9. Python Example

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Age":[22,None,25,999],
    "City":["Delhi","Mumbai","Delhi","Delhi"]
})

print(df)

# Output
#      Age    City
# 0   22.0   Delhi
# 1    NaN  Mumbai
# 2   25.0   Delhi
# 3  999.0   Delhi

# Immediately we can identify
# Missing Value
# Outlier

# These will be handled in preprocessing.

     Age    City
0   22.0   Delhi
1    NaN  Mumbai
2   25.0   Delhi
3  999.0   Delhi

## Topic 2: Why Data Preprocessing is Needed?

### 1. Definition

Data Preprocessing is needed because real-world data is rarely clean, complete, or directly usable for Machine Learning.

Simply put,

**Raw Data ≠ ML Ready Data**

Almost every real-world dataset requires preprocessing before training.

### 2. Why Can't We Train Directly?

Suppose we have the following dataset.

| Age | Salary | City | Experience | Purchased |
|-----|--------|------|------------|-----------|
| 22  | 40000  | Delhi| 1          | No        |
| 25  | 50000  | Mumbai| 2          | Yes       |
| NULL| 60000  | Delhi| 3          | Yes       |
| 25  | 50000  | Mumbai| 2          | Yes       |
| 999 | 700000 | Chennai| 40         | Yes       |
| 30  | 55000  | Bangalore| 5          | No        |

Can we directly do

`model.fit(X, y)`

❌ No.

Because this dataset contains multiple problems.

### 3. Problems in the Dataset ⭐

#### **Problem 1 : Missing Values**

`Age`
`22`
`25`
`NULL`
`30`

**Problem**

Model doesn't know the missing value.

**Solution**

Imputation

We'll study this next.

#### **Problem 2 : Duplicate Data**

| Age | Salary |
|-----|--------|
| 25  | 50000  |
| 25  | 50000  |

**Problem**

Same information repeated.

The model may give this observation extra importance.

**Solution**

Remove Duplicates

#### **Problem 3 : Outliers**

`Salary`
`40000`
`50000`
`55000`
`700000`

`700000` is extremely different.

**Problem**

The model gets distorted.

**Solution**

Detect & Handle Outliers

**Problem 4 : Different Scales**

| Age | Salary |
|-----|--------|
| 22  | 40000  |
| 30  | 55000  |

**Notice**

`Age`

`22`

`30`

`Salary`

`40000`

`55000`

Salary is much larger.

Many ML algorithms will incorrectly treat Salary as more important.

**Solution**

Feature Scaling

#### **Problem 5 : Categorical Values**

`City`
`Delhi`
`Mumbai`
`Chennai`

**Problem**

The computer cannot calculate

`Delhi + Mumbai`

**Solution**

Encoding

#### **Problem 6 : Noisy Data**

`Age`
`22`
`23`
`999`

**Problem**

`999` is likely an error.

**Solution**

Cleaning

#### **Problem 7 : Inconsistent Data**

`Gender`
`Male`
`male`
`M`
`MALE`

**Problem**

Computer thinks these are four different categories.

**Solution**

Standardization

### 4. Complete Picture

Raw Dataset

↓

Missing Values

↓

Duplicates

↓

Noise

↓

Outliers

↓

Encoding

↓

Scaling

↓

Machine Learning

### 5. Why Different Algorithms Need Preprocessing?

| Algorithm         | Needs Scaling? | Needs Encoding? |
|-------------------|----------------|-----------------|
| Linear Regression | ✅ Yes         | ✅ Yes          |
| Logistic Regression| ✅ Yes         | ✅ Yes          |
| KNN               | ✅ Yes         | ✅ Yes          |
| SVM               | ✅ Yes         | ✅ Yes          |
| Neural Networks   | ✅ Yes         | ✅ Yes          |
| Decision Tree     | ❌ Usually No  | ✅ Yes          |
| Random Forest     | ❌ Usually No  | ✅ Yes          |
| XGBoost           | ❌ Usually No  | ✅ Yes          |

**Important:** Almost all algorithms require categorical features to be encoded, but tree-based models usually don't require feature scaling.

### 6. Working

Real World Data

↓

Check Problems

↓

Clean Data

↓

Transform Data

↓

Train Model

↓

Prediction

### 7. Where is it used?

Every ML project.

**Examples**

*   Banking
*   Medical AI
*   Recommendation Systems
*   Stock Prediction
*   Fraud Detection
*   NLP
*   Computer Vision

### 8. Advantages

✅ Higher Accuracy

✅ Better Generalization

✅ Faster Training

✅ Better Predictions

✅ More Stable Models

### 9. Limitations

*   Time consuming
*   Dataset specific
*   Wrong preprocessing can reduce accuracy
*   Requires domain knowledge

### 10. Python Example

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Age":[22,None,25,999],
    "City":["Delhi","Mumbai","Delhi","Delhi"],
    "Salary":[40000,50000,60000,700000]
})

print(df)

# Output
#      Age   City   Salary
# 0   22.0  Delhi    40000
# 1    NaN Mumbai    50000
# 2   25.0 Delhi     60000
# 3  999.0 Delhi    700000

# Problems
# ✓ Missing Value
# ✓ Outlier
# ✓ Categorical Feature
# ✓ Different Scale

     Age    City  Salary
0   22.0   Delhi   40000
1    NaN  Mumbai   50000
2   25.0   Delhi   60000
3  999.0   Delhi  700000

### Problems → Solutions ⭐⭐⭐

| Problem                 | Solution                        |
|-------------------------|---------------------------------|
| Missing Values          | Imputation                      |
| Duplicate Rows          | Remove Duplicates               |
| Categorical Values      | Encoding                        |
| Different Feature Scales| Feature Scaling                 |
| Outliers                | Outlier Detection & Treatment   |
| Inconsistent Values     | Standardization                 |
| Noise                   | Data Cleaning                   |

### Important Note (Order Matters)

One common mistake beginners make is thinking preprocessing steps can be done in any order. In practice, there is a preferred sequence:

0. Raw Data
  
1. Remove Duplicate Rows
  
2. Handle Missing Values
   
3. Fix Inconsistent Values
   
4. Handle Outliers
   
5. Encode Categorical Features
   
6. Scale Numerical Features
   
7. Feature Engineering
   
8. ML Model

## Topic 3: Data Cleaning Pipeline

### 1. Definition

A Data Cleaning Pipeline is a sequence of preprocessing steps applied to raw data to convert it into a clean, consistent, and ML-ready dataset.

Simply put,

**Pipeline = Step-by-step process to clean data.**

### 2. Why do we need a Pipeline?

If we randomly clean data, we may introduce errors. Following a fixed pipeline ensures consistency and prevents issues like data leakage.

### 3. Complete Data Cleaning Pipeline ⭐⭐⭐

1.  **Understand the Dataset**
2.  **Remove Duplicate Records**
3.  **Handle Missing Values**
4.  **Fix Inconsistent Data Formats**
5.  **Handle Outliers**
6.  **Encode Categorical Features**
7.  **Scale Numerical Features**
8.  **Feature Engineering**
9.  **Train/Test Dataset Split**

### 4. Step 1 : Understand the Dataset

Before changing anything, use these Python commands to explore the data structure:

```python
df.head()      # View first few rows
df.info()      # Check data types and non-null counts
df.describe()  # Statistical summary
df.isnull().sum() # Count missing values
```

### 5. Key Steps Breakdown

*   **Step 2: Remove Duplicates** - Bias occurs if the model sees the same info multiple times.
*   **Step 3: Missing Values** - Handled via removal or imputation (Mean/Median/Mode).
*   **Step 4: Inconsistent Data** - Standardizing formats (e.g., 'Male', 'male', 'M' -> 'Male').
*   **Step 5: Outliers** - Detecting and capping or removing extreme values.
*   **Step 6: Encoding** - Converting text to numbers (e.g., One-Hot Encoding).
*   **Step 7: Scaling** - Bringing features like 'Age' and 'Salary' to the same scale.
*   **Step 8: Feature Engineering** - Creating new features (e.g., 'Years of Experience' from 'Joining Date').

### 17. Python Example

In [3]:
import pandas as pd

# Creating the example DataFrame
df_pipeline = pd.DataFrame({
    "Age": [22, None, 25, 25, 999],
    "Salary": [40000, 50000, 50000, 50000, 700000],
    "City": ["Delhi", "Mumbai", "Mumbai", "Mumbai", "Delhi"]
})

print("--- Step 1: Understand the Data ---")
print(df_pipeline.info())

print("\n--- Step 2: Remove Duplicates ---")
df_pipeline = df_pipeline.drop_duplicates()
print(df_pipeline)

print("\n--- Step 3: Check Missing Values ---")
print(df_pipeline.isnull().sum())

--- Step 1: Understand the Data ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     4 non-null      float64
 1   Salary  5 non-null      int64
 2   City    5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
None

--- Step 2: Remove Duplicates ---
     Age  Salary    City
0   22.0   40000   Delhi
1    NaN   50000  Mumbai
2   25.0   50000  Mumbai
4  999.0  700000   Delhi

--- Step 3: Check Missing Values ---
Age       1
Salary    0
City      0
dtype: int64

## Topic 4: Missing Values

### 1. Definition
A Missing Value is a data value that is absent or unknown for a particular observation.

### 2. Why do Missing Values occur?
* Customer didn't fill the form
* Sensor failure
* Data corruption
* Human error

### 3. Why are Missing Values a Problem?
Many ML algorithms (Linear Regression, KNN, SVM) cannot calculate mathematical operations if values are missing.

### 4. Representation
In Pandas, missing data is primarily represented as **NaN** (Not a Number).

### 5. Types of Missing Values ⭐⭐⭐

| Type | Name | Definition | Example |
|------|------|------------|---------|
| **MCAR** | Missing Completely At Random | No relationship with any variable. | Random sensor glitch. |
| **MAR** | Missing At Random | Depends on another observed feature. | Men are less likely to report weight. |
| **MNAR** | Missing Not At Random | Depends on the missing value itself. | High earners not disclosing income. |

### 10. Python Example

In [4]:
import pandas as pd
import numpy as np

df_missing = pd.DataFrame({
    "Age": [22, np.nan, 25, 30]
})

print("--- DataFrame with NaN ---")
print(df_missing)

print("\n--- Boolean Check for Missing Values ---")
print(df_missing.isnull())

print("\n--- Total Missing Values Count ---")
print(df_missing.isnull().sum())

--- DataFrame with NaN ---
    Age
0  22.0
1   NaN
2  25.0
3  30.0

--- Boolean Check for Missing Values ---
     Age
0  False
1   True
2  False
3  False

--- Total Missing Values Count ---
Age    1
dtype: int64

### 6. Advantages of Handling Missing Values

✅ **Better accuracy:** Algorithms can utilize more data.
✅ **More complete dataset:** Prevents loss of valuable rows.
✅ **Better model stability:** Reduces volatility in predictions.

### 7. Limitations

*   **Bias:** Wrong handling (like filling with a constant) can skew results.
*   **Information Loss:** Deleting rows with missing values can waste useful data in other columns.
*   **Complexity:** MNAR data is mathematically difficult to impute correctly.

## Topic 4.1 : Delete Rows (Listwise Deletion)

### 1. Definition
Listwise Deletion means removing the entire row if it contains one or more missing values.

Simply put, **If a row has missing data, throw away the whole row.**

### 2. Why do we use it?
Sometimes only a few rows contain missing values. Instead of guessing the missing value, we simply remove those rows.

### 3. When to use vs. When NOT to use ⭐
*   ✅ **Use when:** Missing values are very few (typically < 5% of the total dataset).
*   ❌ **Don't use when:** Large portions of data are missing (e.g., 70% of rows). Deleting them would leave too little data for the model to learn.

### 4. Advantages & Limitations
*   ✅ **Pros:** Simple, fast, no artificial data added.
*   ❌ **Cons:** Significant loss of information, can introduce bias if missingness isn't random.

In [5]:
import pandas as pd
import numpy as np

# Original Dataset
df_del_rows = pd.DataFrame({
    "Age": [22, np.nan, 25, 30],
    "Salary": [40000, 50000, 60000, 55000]
})

print("--- Before Removing Rows ---")
print(df_del_rows)

# Remove rows with any missing value
df_cleaned_rows = df_del_rows.dropna()

print("\n--- After Removing Rows (dropna) ---")
print(df_cleaned_rows)

--- Before Removing Rows ---
    Age  Salary
0  22.0   40000
1   NaN   50000
2  25.0   60000
3  30.0   55000

--- After Removing Rows (dropna) ---
    Age  Salary
0  22.0   40000
2  25.0   60000
3  30.0   55000

## Topic 4.2 : Delete Columns

### 1. Definition
Delete an entire column if most of its values are missing. If a feature contains too many missing values, remove the feature itself.

### 2. When should we use it?
Usually when a column has **50–80%+ Missing Values** and the feature is not critical for the target prediction.

### 3. Comparison: Delete Rows vs Delete Columns ⭐⭐⭐

| Delete Rows | Delete Columns |
| :--- | :--- |
| Removes observations (rows) | Removes features (columns) |
| Used when few rows are affected | Used when a feature is mostly empty |
| Dataset becomes shorter | Dataset becomes narrower |

### 4. Decision Tree for Missing Values

1. **Is Missingness very small (<5%)?** → Delete Rows.
2. **Is the entire column mostly missing (>50%)?** → Delete Column.
3. **Otherwise?** → Use Imputation (Mean/Median/Mode).

In [6]:
# Example of dropping a column with too many missing values
df_del_cols = pd.DataFrame({
    "Age": [22, 25, 30, 28],
    "Phone": [np.nan, np.nan, np.nan, 987654321]
})

print("--- Before Dropping Column ---")
display(df_del_cols)

# Drop the 'Phone' column because it is 75% missing
df_dropped_col = df_del_cols.drop(columns=["Phone"])

print("\n--- After Dropping 'Phone' Column ---")
display(df_dropped_col)

--- Before Dropping Column ---

   Age        Phone
0   22          NaN
1   25          NaN
2   30          NaN
3   28  987654321.0

--- After Dropping 'Phone' Column ---

   Age
0   22
1   25
2   30
3   28

## Topic 4.3 : Mean Imputation

### 1. Definition
Mean Imputation is the process of replacing missing values in a numerical feature with the average (mean) of the available values.

Simply put, **Replace missing values with the average of the column.**

### 2. Why do we use Mean Imputation?
Instead of deleting valuable rows, we estimate the missing value using the average.

### 3. Formula ⭐⭐⭐
The mean is calculated as:

$$\bar{x} = \frac{\sum x_i}{n}$$

Where:
*   $\bar{x}$ = Mean
*   $x_i$ = Each observed value
*   $n$ = Number of non-missing values

### 4. When to use vs. When NOT to use
*   ✅ **Use when:** Numerical features with approximately Normal Distribution and few outliers.
*   ❌ **Don't use when:** Categorical features (you can't average a city!) or highly skewed data where outliers pull the mean away from the center.

### 5. Advantages & Limitations
*   ✅ **Pros:** Simple, fast, maintains full dataset size.
*   ❌ **Cons:** Highly sensitive to outliers; reduces variance in the dataset artificially.

In [7]:
import pandas as pd
import numpy as np

# Create dataset
df_mean = pd.DataFrame({
    "Age": [20, 22, np.nan, 24, 26]
})

print("--- Original Dataset ---")
print(df_mean)

# Calculate Mean
mean_age = df_mean["Age"].mean()
print(f"\nCalculated Mean: {mean_age}")

# Replace missing value
df_mean["Age"] = df_mean["Age"].fillna(mean_age)

print("\n--- After Mean Imputation ---")
print(df_mean)

--- Original Dataset ---
    Age
0  20.0
1  22.0
2   NaN
3  24.0
4  26.0

Calculated Mean: 23.0

--- After Mean Imputation ---
    Age
0  20.0
1  22.0
2  23.0
3  24.0
4  26.0

## Topic 4.4 : Median Imputation

### 1. Definition
Median Imputation is the process of replacing missing values with the median (middle value) of the available data.

Simply put, **Replace the missing value with the middle value after sorting the data.**

### 2. Why do we use Median Imputation?
The Median is robust and not affected by extreme values (outliers). Whenever data is skewed or contains outliers, Median is preferred over Mean.

### 3. Mean vs Median Comparison ⭐⭐⭐

| Feature | Mean Imputation | Median Imputation |
| :--- | :--- | :--- |
| **Sensitivity** | Highly affected by outliers | Robust to outliers |
| **Best for** | Normal/Symmetric Distribution | Skewed Distribution |
| **Calculation** | Average of all values | Middle value of sorted list |

### 4. Advantages & Limitations
*   ✅ **Pros:** Robust to outliers, works well for skewed distributions (like Salary or House Prices).
*   ❌ **Cons:** Not suitable for categorical data; can distort distribution if missingness is high.

In [8]:
import pandas as pd
import numpy as np

# Dataset with a significant outlier (500,000)
df_median = pd.DataFrame({
    "Salary": [40000, 42000, np.nan, 45000, 500000]
})

print("--- Original Dataset with Outlier ---")
print(df_median)

# Calculate Median
median_val = df_median["Salary"].median()
print(f"\nCalculated Median: {median_val}")

# Replace missing value
df_median["Salary"] = df_median["Salary"].fillna(median_val)

print("\n--- After Median Imputation ---")
print(df_median)

--- Original Dataset with Outlier ---
     Salary
0   40000.0
1   42000.0
2       NaN
3   45000.0
4  500000.0

Calculated Median: 43500.0

--- After Median Imputation ---
     Salary
0   40000.0
1   42000.0
2   43500.0
3   45000.0
4  500000.0

### 6. Working
**Dataset** → **Sort Values** → **Find Middle Value (Median)** → **Replace Missing Value** → **Complete Dataset**

### 7. Where is it used?
Median imputation is preferred for numerical features where data is not normally distributed:
*   **Income/Salary:** Usually skewed by a few high earners.
*   **House Prices:** Real estate data often contains extreme luxury outliers.
*   **Medical Bills:** Costs can vary wildly between standard and specialized treatments.

## Topic 4.5 : Mode Imputation

### 1. Definition
Mode Imputation is the process of replacing missing values with the most frequently occurring value (mode) in a column.

Simply put, **Replace the missing value with the most common value.**

### 2. Why do we use Mode Imputation?
We use it primarily for categorical features where Mean or Median cannot be calculated (e.g., you can't find the "average" of City names).

### 3. Multiple Modes (Bimodal & Multimodal)
Sometimes two or more values occur with the same highest frequency.
*   **Bimodal:** Two modes.
*   **Multimodal:** More than two modes.
*   *Note:* Pandas `.mode()` returns a Series because there can be multiple values. We usually take the first one `[0]`.

### 4. Advantages & Limitations
*   ✅ **Pros:** Works for categorical data, very simple, preserves valid category labels.
*   ❌ **Cons:** Can artificially inflate the majority category and introduce bias; not useful if every value in the column is unique.

In [9]:
import pandas as pd
import numpy as np

# Categorical dataset
df_mode = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Delhi", np.nan, "Delhi"]
})

print("--- Original Dataset ---")
print(df_mode)

# Calculate Mode (returns a Series, so we take index 0)
mode_city = df_mode["City"].mode()[0]
print(f"\nCalculated Mode: {mode_city}")

# Replace Missing Value
df_mode["City"] = df_mode["City"].fillna(mode_city)

print("\n--- After Mode Imputation ---")
print(df_mode)

--- Original Dataset ---
     City
0   Delhi
1  Mumbai
2   Delhi
3     NaN
4   Delhi

Calculated Mode: Delhi

--- After Mode Imputation ---
     City
0   Delhi
1  Mumbai
2   Delhi
3   Delhi
4   Delhi

### 5. When should we use Mode?
✅ **Categorical Features:** City, Gender, Blood Group, Product Category.
✅ **Numerical Features (Discrete):** Ratings (1-5) where specific values are repeated often.

### 6. Working Flow
**Dataset** → **Count Frequency** → **Find Most Frequent Value** → **Replace Missing Value** → **Complete Dataset**

## Topic 4.6 : Constant Value Imputation

### 1. Definition
Constant Value Imputation replaces missing values with a fixed, predefined value.

Simply put, **Replace every missing value with the same constant.**

### 2. Why do we use it?
Sometimes we don't want to guess the missing value (like Mean/Median). Instead, we explicitly indicate that the value is missing using a flag (e.g., -1 for age) or a label (e.g., "Unknown").

### 3. Examples
*   **Numerical:** Missing Salary → `0` or `-1`.
*   **Categorical:** Missing City → `"Unknown"` or `"Missing"`.

### 4. Advantages & Limitations
*   ✅ **Pros:** Very fast, keeps all rows, and preserves the information that the value was originally missing.
*   ❌ **Cons:** A poor choice of constant (like using 0 for Age) can confuse the model; it can introduce artificial patterns if overused.

In [10]:
import pandas as pd
import numpy as np

# 1. Numerical Example (using -1 as a flag)
df_const_num = pd.DataFrame({"Age": [22, np.nan, 25, 30]})
df_const_num["Age"] = df_const_num["Age"].fillna(-1)

print("--- Numerical Constant Imputation (-1) ---")
print(df_const_num)

# 2. Categorical Example (using 'Unknown')
df_const_cat = pd.DataFrame({"City": ["Delhi", "Mumbai", None, "Delhi"]})
df_const_cat["City"] = df_const_cat["City"].fillna("Unknown")

print("\n--- Categorical Constant Imputation ('Unknown') ---")
print(df_const_cat)

--- Numerical Constant Imputation (-1) ---
    Age
0  22.0
1  -1.0
2  25.0
3  30.0

--- Categorical Constant Imputation ('Unknown') ---
      City
0    Delhi
1   Mumbai
2  Unknown
3    Delhi

### 5. Working Flow
**Dataset** → **Find Missing Values** → **Replace with Predefined Constant (C)** → **Complete Dataset**

### Summary: Mean vs Median vs Mode vs Constant ⭐⭐⭐

| Method | Used For | Best When |
| :--- | :--- | :--- |
| **Mean** | Numerical | Normal Distribution (No outliers) |
| **Median** | Numerical | Skewed Data / Many Outliers |
| **Mode** | Categorical | Most Frequent Category exists |
| **Constant** | Both | Missing itself is meaningful (Flagging) |
| **KNN** | Numerical | Correlations exist & dataset is small/medium |

## Topic 4.7 : KNN Imputation (Advanced)

### 1. Definition
KNN (K-Nearest Neighbors) Imputation uses machine learning to fill missing values. It identifies 'K' similar rows based on other available features and uses their values to estimate the missing data.

Simply put, **Look at similar neighbors to guess the missing value.**

### 2. How it Works
1. Calculate the distance (usually Euclidean) between the row with missing data and all other rows.
2. Pick the 'K' closest neighbors.
3. Take the average (for numerical) or most frequent (for categorical) value from those neighbors.

### 3. Advantages & Limitations
*   ✅ **Pros:** Much more accurate than Mean/Median because it considers relationships between features.
*   ❌ **Cons:** Computationally expensive (slow on large datasets); requires numerical data (must encode categories first).

### 4. Decision: When to use?
Use KNN Imputation when you have a small to medium dataset and there are clear correlations between your variables.

In [11]:
from sklearn.impute import KNNImputer
import pandas as pd
import numpy as np

# Sample dataset: Age and Salary are usually related
data = {
    'Age': [20, 25, 30, 45, 50, np.nan],
    'Salary': [30000, 35000, 40000, 80000, 90000, 85000]
}
df_knn = pd.DataFrame(data)

# Initialize KNNImputer (using 2 neighbors)
imputer = KNNImputer(n_neighbors=2)

# Fit and transform
df_filled = pd.DataFrame(imputer.fit_transform(df_knn), columns=df_knn.columns)

print("--- Original Data with Missing Age ---")
print(df_knn)
print("\n--- After KNN Imputation ---")
print(df_filled)

# Notice how the missing age is filled based on the high salary neighbor

--- Original Data with Missing Age ---
    Age  Salary
0  20.0   30000
1  25.0   35000
2  30.0   40000
3  45.0   80000
4  50.0   90000
5   NaN   85000

--- After KNN Imputation ---
    Age   Salary
0  20.0  30000.0
1  25.0  35000.0
2  30.0  40000.0
3  45.0  80000.0
4  50.0  90000.0
5  47.5  85000.0

## Topic 4.8 : Forward Fill (FFill) & Backward Fill (BFill)

### Part A : Forward Fill (FFill)

#### 1. Definition
Forward Fill replaces a missing value with the **last valid value** before it.

Simply put, **Copy the previous value forward.**

#### 2. Why do we use it?
It is primarily used in **Time-Series** data (Stock prices, Temperature, etc.) where we assume the value hasn't changed drastically from the previous moment.

#### 3. Formula
If $x_i = \text{NULL}$, then $x_i = x_{i-1}$

#### 4. Advantages & Limitations
*   ✅ **Pros:** Simple, preserves trends, perfect for sequential data.
*   ❌ **Cons:** Not for random data; can propagate old values too long if many consecutive NaNs exist.

In [12]:
import pandas as pd
import numpy as np

# Time-series like data
df_ffill = pd.DataFrame({
    "Time": ["10:00", "10:05", "10:10", "10:15"],
    "Temp": [25, 26, np.nan, 27]
})

# Apply Forward Fill
df_ffill["Temp_FFill"] = df_ffill["Temp"].ffill()

display(df_ffill)

    Time  Temp  Temp_FFill
0  10:00  25.0        25.0
1  10:05  26.0        26.0
2  10:10   NaN        26.0
3  10:15  27.0        27.0

### Part B : Backward Fill (BFill)

#### 1. Definition
Backward Fill replaces a missing value with the **next valid value**.

Simply put, **Copy the next value backward.**

#### 2. Formula
If $x_i = \text{NULL}$, then $x_i = x_{i+1}$

#### 3. Advantages & Limitations
*   ✅ **Pros:** Useful when future values are a better estimate of the past.
*   ❌ **Cons:** **Data Leakage risk** (using future info to fill past data); usually avoided in forecasting.

In [13]:
# Apply Backward Fill to the same data
df_bfill = pd.DataFrame({
    "Time": ["10:00", "10:05", "10:10", "10:15"],
    "Temp": [25, 26, np.nan, 27]
})

df_bfill["Temp_BFill"] = df_bfill["Temp"].bfill()

display(df_bfill)

    Time  Temp  Temp_BFill
0  10:00  25.0        25.0
1  10:05  26.0        26.0
2  10:10   NaN        27.0
3  10:15  27.0        27.0

### FFill vs BFill

| Property | Forward Fill | Backward Fill |
| :--- | :--- | :--- |
| **Logic** | Uses Previous Value | Uses Next Value |
| **Time-Series** | ✅ Excellent | ⚠️ Use Carefully |
| **Forecasting** | ✅ Preferred | ❌ Usually Avoid |

### When Should We Use Which?

| Dataset Type | Best Method |
| :--- | :--- |
| **Numerical (Normal)** | Mean |
| **Numerical (Skewed)** | Median |
| **Categorical** | Mode |
| **Time-Series** | Forward Fill |